# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('quote', '0003_auto_20170402_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='users',
        ),
        migrations.AddField(
            model_name='favorite',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='log_reg.User'),
        ),
    ]
